'use strict';

Object.defineProperty(exports, "__esModule", {
    value: true
});
const CLIENT_TYPE = exports.CLIENT_TYPE = {
    WECHAT: 'WECHAT',
    IOS: 'IOS',
    ANDROID: 'ANDROID'
};

const APP_TYPE = exports.APP_TYPE = {
    APP: 'APP',
    WECHAT: 'WECHAT'
};

const REDIS_KEY = exports.REDIS_KEY = {
    WECHAT_API_ACCESS_TOKEN: 'wechat_api:access_token',
    WECHAT_API_TICKET_TOKEN: 'wechat_api:ticket_token',
    WECHAT_OAUTH_ACCESS_TOKEN: 'wechat_oauth:access_token',
    MOBILE_VERIFICATION_CODE_CHECK: 'mobile_verification_code_check',
    PWD_CREATE_TOKEN_CHECK: 'pwd_create_token_check',
    MOBILE_CHANGE_TOKEN_CHECK: 'mobile_change_token_check',
    COMMON_TOKEN_CHECK: 'common_token_check',
    PAY_EXTRA: 'pay_extra'
};

const IOU_STATUS = exports.IOU_STATUS = {
    CREATED: 'CREATED', // 已创建
    CONFIRMED: 'CONFIRMED', // 已确认
    REFUSED: 'REFUSED', // 已驳回
    UNDER_REVIEW: 'UNDER_REVIEW', // 待审核
    REVIEW_REJECTED: 'REVIEW_REJECTED', // 审核已拒绝
    UNDER_FNC_REVIEW: 'UNDER_FNC_REVIEW', // 待财务确认
    UNDER_BOW_CONFIRM: 'UNDER_BOW_CONFIRM', // 待借款人确认
    LENDING: 'LENDING', // 生效中
    REPAID: 'REPAID', // 已还清
    CANCELED: 'CANCELED' // 已删除
};

const IOU_EXTENSION_STATUS = exports.IOU_EXTENSION_STATUS = {
    CREATED: 'CREATED',
    CANCELED: 'CANCELED',
    ACCEPTED: 'ACCEPTED',
    REFUSED: 'REFUSED'
};

const USER_TRANSACTION_TYPE = exports.USER_TRANSACTION_TYPE = {
    CHARGE: 'CHARGE',
    WITHDRAW: 'WITHDRAW',
    REPAY: 'REPAY',
    BORROW: 'BORROW',
    IOU_CREATE: 'IOU_CREATE',
    IOU_CANCEL: 'IOU_CANCEL',
    IOU_EXTENSION_CREATE: 'IOU_EXTENSION_CREATE',
    IOU_EXTENSION_CANCEL: 'IOU_EXTENSION_CANCEL'
};

const USER_TRANSACTION_STATUS = exports.USER_TRANSACTION_STATUS = {
    CREATED: 'CREATED',
    CONFIRMED: 'CONFIRMED',
    CANCELED: 'CANCELED'
};

const GROUP_FINANCIAL_TRANSACTION_TYPE = exports.GROUP_FINANCIAL_TRANSACTION_TYPE = {
    CHARGE: 'CHARGE',
    LEND: 'LEND',
    REPAY: 'REPAY',
    EXTEND: 'EXTEND',
    IOU_CREATE: 'IOU_CREATE',
    IOU_CANCEL: 'IOU_CANCEL',
    EXTENSION_CREATE: 'EXTENSION_CREATE'
};

const GROUP_FINANCIAL_TRANSACTION_STATUS = exports.GROUP_FINANCIAL_TRANSACTION_STATUS = {
    CREATED: 'CREATED',
    CONFIRMED: 'CONFIRMED'
};

const USER_SEX_TYPE = exports.USER_SEX_TYPE = {
    MALE: 'MALE',
    FEMALE: 'FEMALE',
    UNKNOWN: 'UNKNOWN'
};

const VERIFICATION_CODE_USAGE_TYPE = exports.VERIFICATION_CODE_USAGE_TYPE = {
    SIGNIN_BY_MOBILE: 'SIGNIN_BY_MOBILE',
    SET_PASSWORD: 'SET_PASSWORD',
    SET_MOBILE: 'SET_MOBILE',
    CHECK_USER_REAL: 'CHECK_USER_REAL',
    BIND_CARD: 'BIND_CARD'
};

const PASSWORD_USAGE_TYPE = exports.PASSWORD_USAGE_TYPE = {
    SET_MOBILE: 'SET_MOBILE'
};

const PUT_ACTION = exports.PUT_ACTION = {
    IOU: {
        CANCEL: 'CANCEL',
        CHANGE: 'CHANGE',
        CONFIRM: 'CONFIRM',
        ACCEPT: 'ACCEPT',
        REFUSE: 'REFUSE',
        DELETE: 'DELETE'
    },
    IOU_EXTENSION: {
        CANCEL: 'CANCEL',
        ACCEPT: 'ACCEPT',
        REFUSE: 'REFUSE'
    },
    IOU_REPAYMENT: {
        ACCEPT: 'ACCEPT',
        REFUSE: 'REFUSE'
    },
    NOTICE: {
        VIEW: 'VIEW'
    },
    COMPLAINT: {
        CANCEL: 'CANCEL'
    }
};

const SEARCH_TYPE = exports.SEARCH_TYPE = {
    IOU: {
        NEED_REPAY: 'NEED_REPAY',
        NEED_COLLECT: 'NEED_COLLECT',
        ALL: 'ALL',
        NOT_IN_EFFECT: 'NOT_IN_EFFECT',
        NEED_CONFIRM: 'NEED_CONFIRM',
        NEED_ACCEPT: 'NEED_ACCEPT',
        IN_EFFECT: 'IN_EFFECT',
        BE_OVERDUE: 'BE_OVERDUE',
        BE_REPAID: 'BE_REPAID'
    },
    CREDIT_DETAIL: {
        AS_LENDER: 'AS_LENDER',
        AS_BORROWER: 'AS_BORROWER',
        BE_OVERDUE: 'BE_OVERDUE'
    }
};

const CONFIG_KEY = exports.CONFIG_KEY = {
    MAX_INTEREST_RATE: 'MAX_INTEREST_RATE',
    MIN_INTEREST_RATE: 'MIN_INTEREST_RATE',
    DEFAULT_LEND_DAYS: 'DEFAULT_LEND_DAYS',
    DEFAULT_EXTEND_DAYS: 'DEFAULT_EXTEND_DAYS',
    IOU_CREATE_FEE: 'IOU_CREATE_FEE',
    IOU_EXTENSION_CREATE_FEE: 'IOU_EXTENSION_CREATE_FEE',
    MAX_IOU_AMOUNT: 'MAX_IOU_AMOUNT',
    DEFAULT_QUOTA: 'DEFAULT_QUOTA',
    REMARK_MAX_LENGTH: 'REMARK_MAX_LENGTH',
    IOS: 'IOS',
    ANDROID: 'ANDROID',
    CUSTOMER_HOTLINE: 'CUSTOMER_HOTLINE',
    CUSTOMER_WECHAT: 'CUSTOMER_WECHAT',
    CUSTOMER_QQ: 'CUSTOMER_QQ',
    COMPLAINT_IMG_STYLE: 'COMPLAINT_IMG_STYLE',
    TEST_ACCOUNT: 'TEST_ACCOUNT',
    SHOW_EDIT_IOUS_BTN: 'SHOW_EDIT_IOUS_BTN',
    DEFAULT_IOU_END_TIME: 'DEFAULT_IOU_END_TIME',
    DEFAULT_IOU_EXTEND_TIME: 'DEFAULT_IOU_EXTEND_TIME',
    SYS_MSG: 'SYS_MSG',
    CHARGE: 'CHARGE',
    WITHDRAW: 'WITHDRAW',
    WITHDRAW_FEE: 'WITHDRAW_FEE'
};

const AMD_CONFIG_KEY = exports.AMD_CONFIG_KEY = {
    GROUP_CONFIG_DEFAULT: 'GROUP_CONFIG_DEFAULT'
};

const NOTICE_TYPE = exports.NOTICE_TYPE = {
    IOU_LENDING: 1,
    IOU_REFUSED: 2,
    IOU_REVIEW_REJECTED: 3,
    IOU_EXTENSION_ACCEPTED: 4,
    IOU_BE_OVERDUE: 5,
    IOU_REPAID: 6
};

const SMS_MSG_TEMPLATE_CODE = exports.SMS_MSG_TEMPLATE_CODE = {
    VERIFICATION_CODE: ''
};

const TMP_MSG_TEMPLATE_ID = exports.TMP_MSG_TEMPLATE_ID = {
    IOU: '',
    IOU_EXTENSION: '',
    IOU_COMPLAINT: ''
};

const ROLE = exports.ROLE = {
    LENDER: 'LENDER',
    BORROWER: 'BORROWER'
};

const COMPLAINT_STATUS = exports.COMPLAINT_STATUS = {
    CREATED: 'CREATED',
    CANCELED: 'CANCELED',
    FINISHED: 'FINISHED'
};

const PUSH_TYPE = exports.PUSH_TYPE = {
    MESSAGE: 'MESSAGE',
    NOTICE: 'NOTICE'
};

const USER_WECHAT_STATUS = exports.USER_WECHAT_STATUS = {
    CREATED: 'CREATED',
    DELETED: 'DELETED'
};

const USER_TYPE = exports.USER_TYPE = {
    LENDER: 'LENDER',
    BORROWER: 'BORROWER'
};

const USER_STATUS = exports.USER_STATUS = {
    ENABLED: 'ENABLED',
    DISABLED: 'DISABLED'
};

const GROUP_STATUS = exports.GROUP_STATUS = {
    ENABLED: 'ENABLED',
    DISABLED: 'DISABLED',
    DELETED: 'DELETED'
};

const CHANNEL_STATUS = exports.CHANNEL_STATUS = {
    ENABLED: 'ENABLED',
    DISABLED: 'DISABLED'
};

const CHANNEL_LENDERS_STATUS = exports.CHANNEL_LENDERS_STATUS = {
    CREATED: 'CREATED',
    DELETED: 'DELETED'
};

const BANK_CARD_STATUS = exports.BANK_CARD_STATUS = {
    CREATED: 'CREATED',
    DELETED: 'DELETED'
};

const ALIPAY_STATUS = exports.ALIPAY_STATUS = {
    CREATED: 'CREATED',
    DELETED: 'DELETED'
};

const SYS_GROUP_ID = exports.SYS_GROUP_ID = 1;

const AUTO_IOU_DEFAULT = exports.AUTO_IOU_DEFAULT = {
    INTEREST_RATE: 24,
    USAGE_TYPE_ID: 9
};

const AUTH_REVIEW_RESULT = exports.AUTH_REVIEW_RESULT = {
    REFUSED: 'REFUSED'
};

const ME_STATUS = exports.ME_STATUS = {
    REFUSED: 'REFUSED',
    TOAUTH: 'TOAUTH',
    CONFIRMING: 'CONFIRMING',
    UNDER_BOW_CONFIRM: 'UNDER_BOW_CONFIRM',
    LENDING: 'LENDING',
    RELOAN: 'RELOAN',
    APPLY: 'APPLY'
};

const USER_APPLY = exports.USER_APPLY = {
    TYPE: {
        RELOAN: 'RELOAN',
        APPLY: 'APPLY'
    },
    STATUS: {
        CREATED: 'CREATED',
        CONFIRMED: 'CONFIRMED'
    }
};

const AUTH_STATUS = exports.AUTH_STATUS = {
    NONE: 'NONE',
    EXPIRE: 'EXPIRE',
    VALIDATE: 'VALIDATE'
};