var gen = function* () {
    yield  console.log("step1")
    yield  console.log("step2")
    yield  console.log("step3")
    yield  console.log("step4")
}
const g = gen()
const next = g.next()
g.next()
g.next()
g.next()
g.next()
g.next()
g.next()
g.next()
g.next()
g.next()
g.next()
g.next()
g.next()
g.next()